Vagrant.configure("2") do |config|

    # VM settings, see https://www.vagrantup.com/docs/vagrantfile/machine_settings.
    config.vm.box = "ubuntu-dev-vm"
    config.vm.hostname = ENV['VM_NAME'] # Does not work, permission denied.
    #config.vm.synced_folder ".", "/vagrant", disabled: true # Disabled, also does not work due to permission denied.
    config.vm.provider "virtualbox" do |v|
        # See https://www.vagrantup.com/docs/providers/virtualbox/common-issues
        # for common issues.
        v.gui = true
        v.name = ENV['VM_NAME']
        #v.memory = ENV['VM_MEMORY'] # Uncomment to enable.
        #v.cpus = ENV['VM_CPUS'] # Uncomment to enable.
    end
    # # Provisioners.
    # # This is a work-around for the config.vm.hostname bug,
    # # where the host name cannot be set due to permission being denied for /etc/hosts.
    # config.vm.provision "shell", path: "./../../scripts/update-hostname.sh", env: {"VM_NAME" => ENV['VM_NAME']}

    # SSH settings, see https://www.vagrantup.com/docs/vagrantfile/ssh_settings.
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
    # # Commands are not escaped somehow.
    # config.ssh.sudo_command = "sudo -E -H -S bash -c '%c'"
    
end